version: 2

models:
  - name: blackhole
    columns: 
      - name: TARGET_FLAG_TARGET
        tests:
            - dbt_expectations.expect_column_values_to_not_be_null:
                row_condition: "TARGET_FLAG_TARGET is not null"
  - name: empx
    columns:

      - name: id
        tests:
          - unique
          - is_null
          - warn_if_odd

      - name: dept
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['IT','GEO','FIN']
              config:
                  severity: warn
                  store_failures: true
                  schema: dbt_tests_results
                  alias: empx_dept

      - name: Hire_Date
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
              config:
                  severity: warn
                  store_failures: true
                  schema: dbt_tests_results
                  alias: empx_hire_date
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "[@]"
              row_condition: "emailId is not Null"
              config:
                severity: error
                store_failures: true
                schema: dbt_tests_results
                alias: empx_emailId_format_checker
        
      - name: sal
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 100
              max_value: 120
              config:
                severity: warn
                store_failures: true
                schema: dbt_tests_results
                alias: empx_sal_out_of_range

          
          